### ISSUE TITLE
ES6 Module support

### ISSUE THREAD

**Issue by sebsobseb** [ArkaneNetwork/web3-arkane-provider#17]
Hi,

I'm trying to import Arkane as a module

```javascript
import Arkane from "@arkane-network/web3-arkane-provider";

...

Arkane.createArkaneProviderEngine(options)
```

But, when i try to call `createArkaneProviderEngine`, this keeps giving me the following error:
**"TypeError: _web3ArkaneProvider.default.createArkaneProviderEngine is not a function"**

I have also created a simple [codesandbox](https://codesandbox.io/s/laughing-field-161h8?file=/src/components/ConnectExample.vue:694-736) example to demo the issue.

Is this not supported yet, or am I doing something wrong?

**Comment by davyvanroy** [comment]
Hi @sebsobseb,

There was a mixup between commonjs/es6 modules.

It should work with the latest version ([0.17.0](https://www.npmjs.com/package/@arkane-network/web3-arkane-provider/v/0.17.0)):
https://codesandbox.io/s/festive-sinoussi-lzopz

Heads up: this won't work from codesandbox since there is origin protection and codesandbox uses generated domains.
